// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	UserID            int64              `json:"user_id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Username          string             `json:"username"`
	Phone             string             `json:"phone"`
	About             string             `json:"about"`
	Birthday          string             `json:"birthday"`
	PersonalChannelID string             `json:"personal_channel_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
