// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AccountsQuantity(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	GetAccount(ctx context.Context, userID int64) (Account, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
