// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AccountsQuantity(ctx context.Context, db DBTX) (int64, error)
	CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) error
	GetAccount(ctx context.Context, db DBTX, userID int64) (Account, error)
	ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
